---
- name: Setup Atlantis
  include_tasks: atlantis.yml
  tags: setup_atlantis

- name: Setup Caddy
  include_tasks: caddy.yml
  tags: setup_caddy

- name: Setup Oauth2 Proxy
  include_tasks: oauth2-proxy.yml
  tags: setup_oauth2_proxy
