---
- name: Reload Caddy
  service:
    name: caddy
    state: reloaded

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Restart Atlantis
  service:
    name: atlantis
    state: restarted

- name: Reload Oauth2 Proxy
  service:
    name: oauth2-proxy
    state: reloaded

- name: Reload Systemd Daemon
  systemd:
    daemon_reload: true
